GET http://localhost:5000/dishes

###

POST http://localhost:5000/dishes
Content-Type: application/json

{ data:
    {
        "name": "Eggs",
        "description": "two scrambled eggs with fresh dill",
        "price": 2,
        "image_url": "https://images.pexels.com/photos/4144234/pexels-photo-4144234.jpeg?h=530&w=350",
    }
}